# coding: utf-8

"""
    Testing code generation using Swagger 2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: tomas.ormisson@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.offer import Offer  # noqa: E501
from swagger_client.rest import ApiException


class TestOffer(unittest.TestCase):
    """Offer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOffer(self):
        """Test Offer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.offer.Offer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
